"""empty message

Revision ID: 8774889f10e0
Revises: 6c0937b35c36
Create Date: 2021-08-07 19:26:07.535378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8774889f10e0'
down_revision = '6c0937b35c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('user_token', sa.String(), nullable=False))
    op.drop_constraint('character_user_id_fkey', 'character', type_='foreignkey')
    op.create_foreign_key(None, 'character', 'user', ['user_token'], ['token'])
    op.drop_column('character', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.create_foreign_key('character_user_id_fkey', 'character', 'user', ['user_id'], ['id'])
    op.drop_column('character', 'user_token')
    # ### end Alembic commands ###
